
#[permalinks]
# post = "/:year/:month/:day/:slug/"
#baseURL = "https://example.com" 
#baseURL = "~/siteLacom/static"
baseURL = ""
disqusShortname = "lacom-ufrgs"
#uglyURLs = true
#baseURL = "/"
#dir = "/home/aqualtune/siteLacom/static"
#relativeURLs = true

#languageCode = "en-us"
#DefaultContentLanguage = "en"
#title = "LACOM Laboratório de Comunicações - UFRGS"
theme = "hugo-theme-techdoc"

#hasCJKLanguage = trueee
metaDataFormat = "yaml"

defaultContentLanguage = "en"
#defaultContentLanguageInSubdir= false
#enableMissingTranslationPlaceholders = false

#aqui codigo novo

[languages]
  [languages.en]
    languageName = "English"
    title = "Networks and Telecommunication Lab LACOM  -  UFRGS"
    description = "Technical document repository"
    weight = 1
#  [[languages.en.menu.main]]
#    url   = "/about/"
 #   name   = "Home us"
   [[languages.en.menu.main]]
    name = "Twitter"
    url = "https://twitter.com/thingsym"
    weight = 2
    
    [languages.pt]
    languageName = "Portuguese"
    title = "Laboratório de Redes e Telecom LACOM  -  UFRGS"
    description = "Repositório de Documentos Técnicos"
    weight = 2
 # [[languages.pt.menu.main]]
 #   slug = "home-pt"
  #  url   = "/"
  #  name   = "Home pt"
  #  weight = 2
  [[languages.pt.menu.main]]
    name = "Twitter"
    url = "https://twitter.com/thingsym"
    weight = 3
# ate aqui


[params]

    # Source Code repository section
    github_repository = "https://github.com/thingsym/hugo-theme-techdoc"
    #version = "0.9.0"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    # title = "LACOM Laboratório de Comunicações"
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
#        "archives",
#        "archive",
#        "blog",
#        "entry",
        "post",
#        "posts",
#        "getting-started",
#        "chapter1",
#        "chapter2",
#        "chapter3"
#	     "gnuradio",
    ]

    # Algolia site search section
    # See https://www.algolia.com/doc/
    algolia_search_enable = true
    algolia_indexName = "hugo-demo-techdoc"
    algolia_appId = "7W4SAN4PLK"
    algolia_apiKey = "cbf12a63ff72d9c5dc0c10c195cf9128" # Search-Only API Key

# Global menu section
# See https://gohugo.io/content-management/menus/
#[menu]
#    [[menu.main]]
#        name = "Home"
#        url = "/"
#        weight = 1

#    [[menu.main]]
#        name = "Twitter"
#        url = "https://twitter.com/thingsym"
#        weight = 2

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 4
        ordered = true

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]
